### ISSUE TITLE
No module named 'PIL'

### ISSUE THREAD

**Issue by bibhuWork** [himansu979/trafficelightclassifier#3]
$ python object_detection/builders/model_builder_test.py
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/home/myfamily/subi/bibhu/models/research/object_detection/builders/model_builder.py", line 29, in <module>
    from object_detection.meta_architectures import ssd_meta_arch
  File "/home/myfamily/subi/bibhu/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 32, in <module>
    from object_detection.utils import visualization_utils
  File "/home/myfamily/subi/bibhu/models/research/object_detection/utils/visualization_utils.py", line 28, in <module>
    import PIL.Image as Image
ModuleNotFoundError: No module named 'PIL'

**Comment by bibhuWork** [comment]
If we directly try to installl PIL 
sudo /home/myfamily/anaconda3/envs/tensorflow/bin/pip install PIL
We might get below error ,
Error : Could not find a version that satisfies the requirement PIL (from versions: )
No matching distribution found for PIL
So instead try installing Image 
sudo /home/myfamily/anaconda3/envs/tensorflow/bin/pip install Image
